server:
  port: 8761

eureka:
  instance:
    hostname: eureka.imaginer.com.br
  client:
    register-with-eureka: false
    fetch-registry: true
  server:
    enable-self-preservation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
