server:
  port: 8761 # Porta padrão do Eureka Server

eureka:
  client:
    register-with-eureka: false # O servidor não se registra nele mesmo
    fetch-registry: false       # O servidor não busca o registro de outros servidores
  server:
    enable-self-preservation: true # Ativa o mecanismo de autopreservação do Eureka (opcional)
  instance:
    preferIpAddress: true
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/actuator/info
    healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/actuator/health
    homePageUrl: http://${eureka.instance.hostname}:${server.port}/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    eureka:
      enabled: true # Habilita verificação de saúde para o Eureka
  info:
    enabled: true # Habilita o endpoint /info
