name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PORT: 22

      - name: Pull latest Docker image from Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker pull ${{ secrets.DOCKERHUB_REPOSITORY }}:latest 

      - name: Stop and remove old container (if exists)
        run: |
          docker ps -a
          docker stop eureka_server || true
          docker rm eureka_server || true
          docker rmi ${{ secrets.DOCKERHUB_REPOSITORY }}:latest || true

      - name: Run new container with the latest image
        run: |
          docker run -d -p 8761:8761 --name eureka_server ${{ secrets.DOCKERHUB_REPOSITORY }}:latest 
